[FIX] l10n_uy_edi: Fix en el manejo de formatos de reporte
ingadhoc/uruguay pull request #231
Opened 2024-10-02 11:51 UTC by mem-adhoc

Ticket: 80829

2024-10-03 20:30 UTC, zaoral requested changes

2024-10-09 18:49 UTC, zaoral requested changes

2024-10-09 18:49 UTC, zaoral commented on l10n_uy_edi/models/l10n_uy_cfe.py
> +        if adenda and len(adenda.splitlines()) >= 5 and 'adenda' not in nombreParametros:
denda.splitlines()) > 6

2024-10-09 18:49 UTC, zaoral commented on l10n_uy_edi/models/l10n_uy_cfe.py
> +                español como en ingles (tambien es un formato disponible en uruware) """
line max lengh 120

2024-10-09 18:49 UTC, zaoral commented on l10n_uy_edi/models/l10n_uy_cfe.py
> +        report_params = safe_eval.safe_eval(self.company_id.l10n_uy_report_params or '[]')
use " instead fof ´

2024-10-09 18:49 UTC, zaoral commented on l10n_uy_edi/models/l10n_uy_cfe.py
> +                el partner de la factura tiene definido algun lenguaje != español: de ser asi imprime el reporte tanto en
identation

2024-10-09 18:49 UTC, zaoral commented on l10n_uy_edi/models/res_company.py
>          return (response, transport) if return_transport else response
add test in this same pr

2024-10-14 14:42 UTC, mem-adhoc commented
Cerramos por cambios de repositorios 
Nuevo branch aca https://github.com/ingadhoc/uruguay/pull/245

2024-10-14 14:42 UTC, closed without merging