[ADD] l10n_uy_ux: new module
ingadhoc/uruguay pull request #243
Opened 2024-10-09 15:08 UTC by zaoral

Task 34526

--

It have evething that is was in our l10n_uy_edi and l10n_uy_account that was not accepted by Odoo

- Rename module to l10n_uy_ux, his will have everything that is not been acepted by odoo
- re add missing addenda things from odoo oficial
- methods and fields renamed
- print legal report from print menu
- button update dgi in move
- create cfe template
- change addenda model, re add apply_on field
- more changes not accepted in official
- more logic for rut/ruc/cie validation
- add more things removed from core
- from odoo
- remove account_withholding module
- change fields and methods
- fix demo data
- adapt demo data adhoc

2024-10-09 15:08 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/uruguay/pull/243).

2024-10-25 16:08 UTC, mem-adhoc commented on l10n_uy_ux/models/account_move.py
> +        if not currency_names:
Aca por que queremos la moneda del movimiento ?
En el caso de que el movimiento tenga configurada una moneda y la comp no, se puede dar este caso ??

2024-10-25 17:12 UTC, mem-adhoc requested changes

2024-10-25 17:12 UTC, mem-adhoc commented on l10n_uy_ux/models/account_move.py
> +            # make sure latest PDF shows to the right of the chatter
este comentario deberia estar en castellano como el resto del archivo!

2024-10-25 17:12 UTC, mem-adhoc commented on l10n_uy_ux/models/account_move.py
> +    def action_l10n_uy_remkark_default(self):
```suggestion
    def action_l10n_uy_remkark_default(self):
    """Agregamos leyedas asociadas al la factura"""
```

2024-10-25 17:12 UTC, mem-adhoc commented on l10n_uy_ux/models/account_move.py
> +            addenda, A16_InfoAdicionalDoc, A51_InfoAdicionalEmisor, A68_InfoAdicionalReceptor, "\n".join(str(item) for item in B8_DscItem))
Quizas esto tenga el mismo resultado y es mas legible! 

```suggestion
messge = (
    f"* Adenda\n{addenda}\n\n"
    f"* Info Adicional Doc\n{A16_InfoAdicionalDoc}\n\n"
    f"* Info Adicional Emisor\n{A51_InfoAdicionalEmisor}\n\n"
    f"* Info Adicional Receptor\n{A68_InfoAdicionalReceptor}\n\n"
    f"* Info Adicional Items\n{'\n'.join(str(item) for item in B8_DscItem)}"
)
```

2024-10-25 17:12 UTC, mem-adhoc commented on l10n_uy_ux/models/account_move.py
> +        """ copy of  _uy_get_legends but return browseables """
idem idioma

2024-10-25 17:12 UTC, mem-adhoc commented on l10n_uy_ux/models/account_move.py
> +        """ Do not let to create not invoices entries in journals that use documents """
idem idioma

2024-10-25 17:12 UTC, mem-adhoc commented on l10n_uy_ux/models/l10n_uy_edi_document.py
> +            Message if there is a problem or something missing """
```suggestion
        """ Intenta mandar mensaje de error de alerta si estas en ambiente de testing con datos
        de produccion

        Return:
            False: si no hay errores,
            Message: si hay errores o falta algo """
```

2024-10-25 17:12 UTC, mem-adhoc commented on l10n_uy_ux/models/l10n_uy_edi_document.py
> +        return versionPdf, extra_params
Quizas sea mejor dejarlo como lo tenemos en v16, o quizas queres que los hagamos posteriormente

```suggestion
     def _get_report_params(self):
        """ Modificamos para que al generar el PDF no genere el formato standard sino lo genere tomando en cuenta
        lo siguiente:

        1. En caso que el cliente tenga definido un reporte en los ajustes de sistema, sea porque tenga un reporte
            personalizado o preferencia de imprimir algún otro formato,
        2. En caso de que el comprobante tenga adendas con textos muy largos (mayor a 799 caracteres) si imprime
            el formato standard va a hacer que salga cortada. en este caso si vemos que algun comprobante cumple
            esta condición entonces la adenda  se imprimira en una pagina separada (adenda en segunda pagina -
            es un formato disponible en uruware)
        3.  En caso de que el documento sea un e-ticket o e-factura expo o sus respectivas NC y ND se fijara si
            el partner de la factura tiene definido algun lenguaje != español: de ser asi imprime el reporte tanto en
            español como en ingles (tambien es un formato disponible en uruware)
        """
        compatible_en = ['101', '102', '103', '121', '122', '123']
        adenda = self._l10n_uy_get_cfe_adenda().get('Adenda')
        report_params = safe_eval.safe_eval(self.company_id.l10n_uy_report_params or "[]")
        nombreParametros = report_params[0] if report_params else []
        valoresParametros = report_params[1] if report_params else []
        if adenda and len(adenda.splitlines()) > 6 and 'adenda' not in nombreParametros:
            nombreParametros.append('adenda')
            valoresParametros.append('true')
        if self.l10n_latam_document_type_id.code in compatible_en:
            if self.partner_id.lang and 'es' not in self.partner_id.lang and 'ingles' not in valoresParametros:
                nombreParametros.append('reporte')
                valoresParametros.append('ingles')
        elif 'ingles' in valoresParametros:
            nombreParametros.remove('reporte')
            valoresParametros.remove('ingles')

        return nombreParametros, valoresParametros
```

2024-10-25 17:12 UTC, mem-adhoc commented on l10n_uy_ux/models/res_partner.py
> +        """ Only used for """
Creo que aca te olvidaste de poner el resto del comentario!

2024-10-26 11:51 UTC, zaoral commented on l10n_uy_ux/models/account_move.py
> +        if not currency_names:
la intencion era verificar que la monedas esten configuradas, buena Maxi, en si el movimiento podria no tener moneda, lo modifoco para que tome solo la de la compania

2024-10-26 11:54 UTC, zaoral commented on l10n_uy_ux/models/account_move.py
> +            # make sure latest PDF shows to the right of the chatter
en realidad me gustaria que todo este en ingles,  de ultima vemos de charlarlo con el equipo y definimos si todo en ingles o todo en espealñol. Por lo pronto en este pr y lo que tenemos pasado el deadline no lo cambiaria, sino un pr REF a posteriori

2024-11-01 20:35 UTC, pablohmontenegro requested changes

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/i18n/es.po
> +# Translation of Odoo Server.
@zaoral  por que es.po y no es_419.po ?

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/i18n/es.po
> +msgstr ""
add translation

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/i18n/es.po
> +msgstr ""
add translation

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/i18n/es.po
> +msgstr ""
add translation

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/i18n/es.po
> +msgstr ""
add translation

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/i18n/es.po
> +msgstr ""
add translation

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/i18n/es.po
> +msgstr ""
add translation

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/i18n/es.po
> +msgstr ""
add translation

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/i18n/es.po
> +"                        Select the list of fields you want to update."
add translation

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/i18n/es.po
> +msgid "There are no more partners to update for this request..."
add translation

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/i18n/es.po
> +msgid "There was a problem with the connection, this is what we get: "
add translation

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +        self.ensure_one()
```suggestion
```
creo que no haría falta ya que en la línea siguiente se llama en el super

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +        if self.journal_id.type == "sale" and self.journal_id.l10n_uy_edi_type not in ["electronic", "manual"]:
conviene hacer l10n_uy_edi_type requerido en el diario si es de ventas uruguayo? igual veo que en el método computado de l10n_uy_edi_type si el diario es de tipo sale entonces l10n_uy_edi_type es electronic

2024-11-01 20:35 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +                    "\n - 22% Sales VAT\n - 10% Sales VAT\n - Exempt Sales VAT", company_name=company.name))
conviene hacer esto acá en este método _l10n_uy_edi_check_move ? o es mejor por un tema de performance performance hacer una constrains para que no se eliminen o modifiquen los impuestos de ventas al 22%, 10%, 0% ? además en todos los casos siempre queremos ver que existan esos 3 impuestos? que pasa si la factura no tiene esos 3 impuestos y usa uno solo?

2024-11-04 18:59 UTC, zaoral commented on l10n_uy_ux/i18n/es.po
> +# Translation of Odoo Server.
gracias @pablohmontenegro habia quedado viejo, ahi lo cambie para que use es_149, borre el es.po y agregue los terminos, en un ratito hago el push

2024-11-07 19:40 UTC, pablohmontenegro requested changes

2024-11-07 19:40 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +    # TODO KZ hacer pr a 17 o master pidiendo que hagan este fix directamtne en el modulo de l10n_latam_base
```suggestion
    # TODO KZ hacer pr a 17 o master pidiendo que hagan este fix directamtne en el modulo de l10n_latam_invoice_document
```

2024-11-07 19:40 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +        cuando la factura aun esta en borrador
pero veo que acá https://github.com/ingadhoc/uruguay/pull/243/files#diff-ea8cd580fa5df541047dbf2abe4aadf254a6558a05a74307a6b50a55372e6b4fR60 dice " invisible="state != 'draft' ", entonces se puede visualizar incluso cuando el contenido el xml está en borrador?

2024-11-07 19:40 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +            self.invoice_date = False
```suggestion
        not_invoice_date = not self.invoice_date
        if not_invoice_date:
            self.invoice_date = fields.Date.today()
        self.l10n_uy_cfe_xml = self._l10n_uy_edi_get_xml_content().encode()
        if not_invoice_date:
            self.invoice_date = False
```

2024-11-07 19:40 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +        if not_invoice_dat:
consulto: por qué volvemos a hacer "if not_invoice_dat:" y lo establecemos self.invoice_date = False ? podrías agregar un comentario explicando?

2024-11-07 19:40 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +        uy_docs = self.env["l10n_latam.document.type"].search([("country_id.code", "=", "UY")])
```suggestion
```
sacar esta línea y moverla abajo (arriba del move.write...)

2024-11-07 19:40 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +        self.l10n_uy_edi_document_id = edi_doc
por que hacemos esto? podrías agregar un comentario explicando?

2024-11-07 19:40 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +    def action_l10n_uy_mandatory_legend(self):
add docstring

2024-11-07 19:40 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +        return bool(self.fiscal_position_id and "zona franca" in self.fiscal_position_id.name.lower())
es necesario este método?

2024-11-07 19:40 UTC, pablohmontenegro commented on l10n_uy_ux/models/l10n_uy_edi_document.py
> +import re
```suggestion
```

2024-11-07 19:40 UTC, pablohmontenegro commented on l10n_uy_ux/models/l10n_uy_edi_document.py
> +        response = result.get("response")
result es definido en el if anterior, hacer las correcciones necesarias si no se entra en ese if

2024-11-07 20:00 UTC, pablohmontenegro requested changes

2024-11-07 20:00 UTC, pablohmontenegro commented on l10n_uy_ux/models/res_company.py
> +from odoo import _, fields, models
```suggestion
from odoo import fields, models
```

2024-11-07 20:00 UTC, pablohmontenegro commented on l10n_uy_ux/models/res_company.py
> +from odoo.tools.zeep.wsse.username import UsernameToken
```suggestion
```

2024-11-07 20:00 UTC, pablohmontenegro commented on l10n_uy_ux/models/res_company.py
> +    def uy_ux_action_update_from_config(self):
dónde se llama este método? agregar docstring

2024-11-07 20:00 UTC, pablohmontenegro commented on l10n_uy_ux/models/res_partner.py
> +import pprint
```suggestion
```

2024-11-07 20:00 UTC, pablohmontenegro commented on l10n_uy_ux/models/res_partner.py
> +from xml.etree.ElementTree import fromstring, ElementTree
```suggestion
from xml.etree.ElementTree import fromstring
```

2024-11-08 12:40 UTC, pablohmontenegro requested changes

2024-11-08 12:40 UTC, pablohmontenegro commented on l10n_uy_ux/models/res_partner.py
> +        msg = self._l10n_uy_edi_identification_validation()
dónde se define _l10n_uy_edi_identification_validation() ?

2024-11-08 12:40 UTC, pablohmontenegro commented on l10n_uy_ux/views/account_move_views.xml
> +                <attribute name="context">{"default_type": "item", "default_apply_on": "account.move", "form_view_ref": "l10n_uy_edi.l10n_uy_edi_addenda_view_form_only_item"}</attribute>
hace falta default_apply_on?

2024-11-08 12:40 UTC, pablohmontenegro commented on l10n_uy_ux/views/cfe_template.xml
> +</odoo>
queremos mezclar este archivo? si hay que borrarlo entonces corresponde sacarlo del manifest tmb

2024-11-08 12:40 UTC, pablohmontenegro commented on l10n_uy_ux/views/l10n_uy_addenda_views.xml
> +        <field name="context">{"active_test": False}</field>
por que queremos agregar {"active_test": False} ? fue testeado funcionalmente?

2024-11-08 12:40 UTC, pablohmontenegro commented on l10n_uy_ux/wizards/res_partner_update_from_padron_uy_wizard.py
> +
can you add docstring to the methods?

2024-11-11 12:13 UTC, zaoral commented on l10n_uy_ux/views/l10n_uy_addenda_views.xml
> +        <field name="context">{"active_test": False}</field>
Si. queremos que este el active_test para que al entrar en la viste muestre tanto las addendas activas como las inactivas. si no tenemos este active test, mostraria solo las adendas activas

2024-11-11 12:14 UTC, zaoral commented on l10n_uy_ux/wizards/res_partner_update_from_padron_uy_wizard.py
> +
Me parece bien, pero esto es una copia del que tenemos en argentina. y quisiera que quedaran lo mas parecidos posibles para que en version 18 mezclar estos dos wizards en uno solo, y ahi si poder mejorarlo y dejarlo documentando y detallado.

2024-11-11 12:21 UTC, zaoral commented on l10n_uy_ux/models/account_move.py
> +        uy_docs = self.env["l10n_latam.document.type"].search([("country_id.code", "=", "UY")])
Si lo coloque en el for. se repetiria multiples veces. esta bien si queda fuera del for?

2024-11-11 12:25 UTC, zaoral commented on l10n_uy_ux/views/account_move_views.xml
> +                <attribute name="context">{"default_type": "item", "default_apply_on": "account.move", "form_view_ref": "l10n_uy_edi.l10n_uy_edi_addenda_view_form_only_item"}</attribute>
Si. para que cuando creemos una nueva addenda desde este menu sepa que es de tipo tickets y facturas
https://drive.google.com/file/d/1ycQe11td0C17qSQAzuc7rKcnViW81ytx/view

2024-11-11 12:26 UTC, zaoral commented on l10n_uy_ux/models/res_partner.py
> +        msg = self._l10n_uy_edi_identification_validation()
gracias pablito, este metodo lo habiamos corrado, asi que no tiene sentido que este el onchange

2024-11-11 12:28 UTC, zaoral commented on l10n_uy_ux/models/res_company.py
> +    def uy_ux_action_update_from_config(self):
era un boton para recargra la info del ambiente de los campos texto que tenemos, ya no tenemos el boton asi que elimino el metodo

2024-11-11 16:09 UTC, zaoral commented on l10n_uy_ux/views/cfe_template.xml
> +</odoo>
gracias pablito, ahi ya lo elimine

2024-11-11 16:10 UTC, zaoral commented on l10n_uy_ux/models/account_move.py
> +        return bool(self.fiscal_position_id and "zona franca" in self.fiscal_position_id.name.lower())
lo usan los condition de las addendas
solo para simplificar el saber si viene o no de una zona franca

2024-11-11 20:05 UTC, zaoral commented on l10n_uy_ux/models/account_move.py
> +        if not_invoice_dat:
Pablito la razon es para que pueda funcionar necesitamos tener definido la fecha de factura porque sino el xml falla, por eso en este metodo temporalmente asignamos la fecha de factura a la de hoy y luego la borramos para que quede l factura tal cual estaba. lo deje como comentario en el codigo. si te parece que hace falta sumar algo mas no dudes en avisar

2024-11-11 20:07 UTC, zaoral commented on l10n_uy_ux/models/account_move.py
> +        self.l10n_uy_edi_document_id = edi_doc
pablito, agregado en el docstring
"""
        To make the validation of the CFE and connect to uwaure we need to have a EDI document
        For that reason if we have one we delete it and create a new one with the result of
        the validation, since we are raising and the end of the method then the edi document
        is rolled back 
"""

2024-11-11 20:12 UTC, zaoral commented on l10n_uy_ux/models/account_move.py
> +        cuando la factura aun esta en borrador
Si en este caso queremos mostrar este boton nuevo de preview cuando estamos en borrador. y si estamos en otro estado entonces mostramos el boton preview que ya tiene odoo. serian dos botones por sepados

2024-11-11 20:18 UTC, zaoral commented on l10n_uy_ux/models/account_move.py
> +                    "\n - 22% Sales VAT\n - 10% Sales VAT\n - Exempt Sales VAT", company_name=company.name))
si, seria mejor hacerlo en otro lado. me queda la duda si deberia ser en un constraint. o tal vez en unlink() o write()? Lo comento por ahora, en donde crees que seria mejor dejarlo?

En el caso como esta, si la factura usa solo un impuesto, si hay algun error de configuracion (no existe otro impuesto) no deja validar hasta tanto no lo corrija.

2024-11-11 20:20 UTC, zaoral commented on l10n_uy_ux/models/account_move.py
> +        if self.journal_id.type == "sale" and self.journal_id.l10n_uy_edi_type not in ["electronic", "manual"]:
ya el campo l10n_uy_edi_type  esta requerido. dejamos esto por las dudas, la gente que capaz tenia definido el diario previo a la instalacion del modulo de l10n_uy_edi (como sucede cuando migramos bases de 16 a 17 y queda el campo de cuentas contable vacio y no da error solo si queremos modifcar el diario). esto seria para asegurar siempre este configurado no importa que. si te parece que esta de mas lo podemos quitar

2024-11-13 12:00 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +        if self.journal_id.type == "sale" and self.journal_id.l10n_uy_edi_type not in ["electronic", "manual"]:
está bien así Kathy, lo dejamos así entonces, gracias por la explicación, podes marcar como resuelto mi comentario.

2024-11-13 12:17 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +                    "\n - 22% Sales VAT\n - 10% Sales VAT\n - Exempt Sales VAT", company_name=company.name))
Gracias Kathy, creo que lo menos invasivo sería un unlink() en account.tax

2024-11-13 12:19 UTC, pablohmontenegro commented on l10n_uy_ux/models/account_move.py
> +        uy_docs = self.env["l10n_latam.document.type"].search([("country_id.code", "=", "UY")])
está bien, lo podemos dejar como está

2024-11-13 12:20 UTC, pablohmontenegro commented on l10n_uy_ux/wizards/res_partner_update_from_padron_uy_wizard.py
> +
Perfecto! lo dejamos así entonces

2024-11-15 12:22 UTC, pablohmontenegro commented
@roboadhoc r+

2024-11-15 12:26 UTC, closed without merging