[MIG] l10n_uy_edi_stock: version 17.0
ingadhoc/uruguay pull request #244
Opened 2024-10-09 15:15 UTC by zaoral

- cosas que movimos de l10n_uy_edi que nos pidieron quitaramos
- adaptando modelo cfe, y trayendo tolo que no nos aceptaron adaptandolo para que funcione como un modelo normal y no un mixin
- get dgi state button
- update methods and field renamed
- move stuff from l10n uy edi official
- UY transport
- add constraint not sure yet
- place of delivery boolean
- TipoTraslado
- move template to views
- replace fields

---
Task 37187 (stock)

2024-10-09 15:15 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/uruguay/pull/244).

2024-11-07 14:26 UTC, zaoral commented on l10n_uy_edi_stock/models/l10n_uy_addenda.py
> +    ])
comentarlo de manera temporal, mientras que esta el merge de l10n_uy_ux
ya con esto deberia de poder avanzar con el resto de las pruebas para ver que funcione el remito electronico
@mem-adhoc

2024-11-07 15:31 UTC, mem-adhoc commented on l10n_uy_edi_stock/models/l10n_uy_addenda.py
> +    ])
Kathyyy listo el cambio, podrias marcarlo como resuelto ?? yo no puedo no se por que jeje

2024-11-07 17:06 UTC, mem-adhoc commented on l10n_uy_edi_stock/models/l10n_uy_addenda.py
> +    ])
@zaoral

2025-04-08 16:01 UTC, pablohmontenegro requested changes

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/data/l10n_latam.document.type.csv
> +"l10n_uy.dc_e_remito","stock_picking",True
Why "l10n_uy.dc_e_remito" is [active: "True"] and the other lines not?

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/l10n_uy_edi_document.py
> +        # EXTEND from l10n_uy_ux
this method does not exist on l10n_uy_ux

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +        compute=lambda self: self._compute_linked_attachment_id('edi_pdf_report_id', 'edi_pdf_report_file'),
```suggestion
        compute=lambda self: self.env['l10n_uy_edi.document']._compute_linked_attachment_id('edi_pdf_report_id', 'edi_pdf_report_file'),
```

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +        compute=lambda self: self._compute_linked_attachment_id('edi_pdf_report_id', 'edi_pdf_report_file'),
I think that _compute_linked_attachment_id method defined in this file could be deleted

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +        if self.l10n_uy_transfer_of_goods:
add docstring explaining code 181 --> e-Delivery Guide

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +        en este metodo temporalmente asignamos la fecha de factura a la de hoy y luego la borramos para que quede la
no vi donde se establece la fecha de la factura ni donde se borra, te parece agergar alguna referencia?

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +        en este metodo temporalmente asignamos la fecha de factura a la de hoy y luego la borramos para que quede la
está comentado el botón que lo llama https://github.com/ingadhoc/uruguay/pull/244/files#diff-5f7502cec1021b2010945914061a2c3ce1fd553a923e8c818894ed17c5204d4bR64

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +    def uy_stock_action_validate_cfe(self):
está comentado el botón que llama este método https://github.com/ingadhoc/uruguay/pull/244/files#diff-5f7502cec1021b2010945914061a2c3ce1fd553a923e8c818894ed17c5204d4bR65

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +    def _compute_l10n_uy_is_cfe(self):
"for rec in self" could be neccesary?

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +        # TODO KZ this should not be neceesary :(
something to do with this?

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +        if self.origin:
why self.origin?

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +    def _l10n_uy_edi_get_used_rate(self):
is used this method?

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +        return abs(self.amount_total_signed) / self.amount_total
```suggestion
        return abs(self.amount_total_signed) / self.amount_total if self.amount_total else 0.0
```

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +    def _l10n_uy_get_delivery_guide_codes(self):
this method is called once, i think it could be avoided

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +                doc_number = response.findtext(".//{*}NumeroCfe")
de acuerdo al comentario anterior "EL response no me trae los datos que necesito, solamente me trajo" estos datos no existen en la response entonces no se va a poder hacer el write de abajo

2025-04-08 16:01 UTC, pablohmontenegro commented on l10n_uy_edi_stock/models/stock_picking.py
> +            "Ciudad": self.company_id.city[:30],
city could be False. We can´t do False[:30]

2025-04-08 18:00 UTC, zaoral commented on l10n_uy_edi_stock/models/stock_picking.py
> +        en este metodo temporalmente asignamos la fecha de factura a la de hoy y luego la borramos para que quede la
eliminar el comentario que habla de la factura y la fecha, aca no tiene sentido

2025-04-08 18:10 UTC, zaoral commented on l10n_uy_edi_stock/models/stock_picking.py
> +    def _l10n_uy_edi_get_used_rate(self):
comentar

2025-04-08 18:15 UTC, zaoral commented on l10n_uy_edi_stock/models/stock_picking.py
> +                doc_number = response.findtext(".//{*}NumeroCfe")
comentar este metodo hasta tanto no lo arreglemos
uy_stock_action_get_uruware_cfe

2025-04-11 13:57 UTC, zaoral commented on l10n_uy_edi_stock/models/stock_picking.py
> +        # TODO KZ this should not be neceesary :(
por el momento no conseguimos mejor solucion, lo dejamos como un TODO en el codigo

2025-04-14 18:43 UTC, pablohmontenegro commented
@roboadhoc r+

2025-04-14 18:43 UTC, zaoral commented
@roboadhoc rebase-ff

2025-04-14 18:44 UTC, roboadhoc commented
Merge method set to rebase and fast-forward.

2025-04-14 18:46 UTC, closed without merging