[FIX] l10n_uy_edi: e-invoice line wo product
ingadhoc/uruguay pull request #252
Opened 2024-10-24 20:18 UTC by zaoral

Ticke 82127

2024-10-24 20:19 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/uruguay/pull/252).

2024-10-28 15:04 UTC, mem-adhoc requested changes

2024-10-28 15:04 UTC, mem-adhoc commented on l10n_uy_edi/models/l10n_uy_cfe.py
>                  res.append(line.name)
En el caso de que nosotros quisieramos colocar una linea sin product_id esto no funcionaria.
```suggestion
            if line.name and line.product_id and line.name != line.product_id.display_name or line.name and not line.product_Id:
                res.append(line.name)
```

2024-10-28 15:30 UTC, mem-adhoc commented
@roboadhoc r+

2024-10-28 15:33 UTC, closed without merging