[MIG] l10n_uy_currency_update: Migration to 18.0
ingadhoc/uruguay pull request #257
Opened 2024-10-31 13:26 UTC by mem-adhoc

2024-10-31 13:27 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/uruguay/pull/257).

2024-11-25 13:19 UTC, zaoral requested changes

2024-11-25 13:19 UTC, zaoral commented on l10n_uy_currency_update/__manifest__.py
>          'views/res_currency_views.xml',
remove  'summary': '',

2024-11-25 13:19 UTC, zaoral commented on l10n_uy_currency_update/__manifest__.py
>      'application': False,
remove store=False of field l10n_uy_have_bcu_code

2024-11-25 13:19 UTC, zaoral commented on l10n_uy_currency_update/__manifest__.py
>  }
change variable rate with rates

2024-11-25 13:19 UTC, zaoral commented on l10n_uy_currency_update/__manifest__.py
>  }
improve method _compute_l10n_uy_bcu_have_code,

- replace _parse_bcu_data with _get_bcu_currencies_mapping (Please check special case of UYI)
- you hwave a for and and if, you can simplify with two lines and a filtered

2024-11-25 13:19 UTC, zaoral commented on l10n_uy_currency_update/__manifest__.py
>  }
Change method to do not compute all the rates. only the rate we want of the current currency

```python
    def action_l10n_uy_get_bcu_rate(self):
        self.ensure_one()
        date_api_client = Client(wsdl % 'awsultimocierre')
        last_closing_date = date_api_client.service.Execute()
        
        rate = self.env['res.company']._parse_bcu_data(self)
        if rate:
            raise UserError(_('Fecha Ultimo Cierre: %s\nRate: %s' % (rate[self.name][1], rate[self.name][0])))
        raise UserError(_('No se encontro cotizacion para esta Moneda'))
```

2024-11-25 13:19 UTC, zaoral commented on l10n_uy_currency_update/__manifest__.py
>  }
Please all the lines max 120 chars

2024-11-25 13:19 UTC, zaoral commented on l10n_uy_currency_update/__manifest__.py
>  }
Add logic to shod/hide buttons of the buttons in the res.currency form view

2024-12-04 21:44 UTC, zaoral commented
@roboadhoc r+

2024-12-04 21:50 UTC, closed without merging