[IMP] l10n_uy_currency_update: We change the last closing day and some changes in the views
ingadhoc/uruguay pull request #269
Opened 2024-12-05 19:21 UTC by mem-adhoc

Task: 43301

2024-12-05 19:22 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/uruguay/pull/269).

2024-12-11 11:47 UTC, zaoral requested changes

2024-12-11 11:47 UTC, zaoral commented on l10n_uy_currency_update/views/res_currency_views.xml
> +                    <button name="action_get_available_currencies" invisible="l10n_uy_have_bcu_code or fiscal_country_codes != 'UY'" type="object" class="btn-link" string="⇒ (UY) Obtener info monedas
Hi @mem-adhoc 
I test this and it is not working functionally
fiscal_country_codes string that store the info of a list. So the possible values could be for example

* ["UY"]
* ["UY", "AR"]
* ["AR"]

you can not compare != "UY" because the button is never shown in the view.
you should use somethinh like `"UY" not in fiscal_country_codes`

Also in order to make it work please re order the conditions so will show or not the buttons when needed

Best Regards

2024-12-18 14:15 UTC, zaoral commented
@roboadhoc r+

2024-12-18 14:20 UTC, closed without merging